version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our 
volumes:
  db_data: